- name: Install {{ app.name }} from AppStore
  block:
    - name: Check if {{ app.name }} is installed
      shell: "mas list | grep -oq '.*{{ app.id }}.*'"
      register: mas_install_check
      ignore_errors: True
      changed_when: False

    - name: Install {{ app.name }}
      when: mas_install_check.rc != 0
      shell: "mas install '{{ app.id }}'"
