- name: Install Tmux Plugin Manager  
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    ssh_opts: '-o StrictHostKeyChecking=no'
    update: False

- name: Create symlink ~/work/journals to Google Drive journals
  file:
    src: "{{ lookup('env', 'HOME') }}/genzer_hawker/google_drive/genzerhawker/journals"
    dest: "{{ lookup('env', 'HOME') }}/work/journals"
    state: link

- name: Is Finder show all hidden files?
  shell: defaults read com.apple.finder AppleShowAllFiles
  register: finder_show_all_files
  changed_when: False

- name: set MacOS to show hidden files/directories
  when: finder_show_all_files.stdout != '1'
  shell: defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder

- name: Install Mac OS Applications from AppStore
  include_tasks: install_mac_os_applications.yaml
  vars:
    app: "{{ item }}"
  loop:
    - "Be Focused"
    - "Microsoft Remote Desktop 10"