- name: Create symlink ~/work/journals to Google Drive journals
  file:
    src: "/Volumes/GoogleDrive/My\ Drive/genzerhawker/journals"
    dest: "{{ lookup('env', 'HOME') }}/work/journals"
    state: link

- name: Is Finder show all hidden files?
  shell: defaults read com.apple.finder AppleShowAllFiles
  register: finder_show_all_files
  ignore_errors: True
  changed_when: False

- name: set MacOS to show hidden files/directories
  when: finder_show_all_files.stdout != '1'
  shell: defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder
