- name: Configure ~/.docker/config.json to use the ecr-login
  import_role:
    name: genzer.utils
    tasks_from: json_file
  vars:
    dest: "~/.docker/config.json"
    update_content: |
      {
        "credHelpers": {
          "031813119665.dkr.ecr.ap-southeast-1.amazonaws.com": "ecr-login",
          "031813119665.dkr.ecr.eu-central-1.amazonaws.com": "ecr-login"
        }
      }
