- name: Install all commands using Homebrew.
  hosts: localhost
  tags:
    - brew
  vars:
    homebrew_use_brewfile: true
    homebrew_brewfile_dir: '{{playbook_dir}}'
  roles:
    - geerlingguy.mac.homebrew

- name: Setting up workspace.
  hosts: localhost
  tags:
    - workspace
  roles:
    - role: genzer.workspace
      tags:
        - workspace.apps

collections:
  - name: geerlingguy.mac
