- name: Install all commands using Homebrew.
  hosts: localhost
  tags:
    - commands
  vars:
    homebrew_taps:
      - homebrew/core
      - mike-engel/jwt-cli

    homebrew_installed_packages:
      - { name: vim, install_option: "with-override-system-vim" }
      - git
      - tmux
      - zsh
      - thefuck
      - ack
      - jenv
      - awscli
      # An awesome utility to ovewrite default `/bin/rm`
      # so that deleted files/directories go to the Trash
      # instead of being permanently deleted.
      - trash
      # utility for installing MacOS application from Store
      # https://github.com/mas-cli/mas
      - mas
      - hadolint
      - nvm
      - findutils
      - todo-txt
      - watch
      - tree
      - jq
      - python-yq
      - go
      - gnu-sed
      - maven
      - wget
      - gradle
      - groovy
      - asciinema
      - htop
      # For developing AWS Lambda
      - serverless
      - python@3.8
      # VSCode PlantUML Preview
      - graphviz
      # A useful to see Disk Usage
      - ncdu
      - jwt-cli
      - bat
      - openshift-cli

    homebrew_uninstalled_packages:
      # antigen slows down the startup time of zsh.
      - antigen
      - powerlevel9k
  pre_tasks:
    - name: Ensure ask-become-pass is working
      shell: id
      become: True
  roles:
    - geerlingguy.homebrew

- name: Installing MacOS Applications using Homebrew.
  hosts: localhost
  tags:
    - apps
  vars:
    homebrew_taps:
      - homebrew/cask-versions
      - homebrew/cask-fonts
    homebrew_cask_apps:
      - google-chrome
      - sublime-text 
      - iterm2
      - skype
      - postman
      - visual-studio-code
      - slack
      - viscosity
      - vlc
      - keka
      - the-unarchiver
      - franz
      - xquartz
      - typora
      - teamviewer
      - snagit
      - enpass
      - onedrive
      - keycastr
      - docker
      - balsamiq-mockups
      - font-fira-mono
      - font-fira-mono-for-powerline
      - google-backup-and-sync
      - gas-mask
      - adobe-acrobat-reader
      - robo-3t
      - font-hack-nerd-font
      - angry-ip-scanner
      - visualvm
      - ngrok
      - webex-meetings
      - microsoft-teams
      - pgadmin4

  pre_tasks:
    - name: Ensure ask-become-pass is working
      shell: id
      become: True
  roles:
    - geerlingguy.homebrew

- name: Setting up workspace.
  hosts: localhost
  tags:
    - workspace
  roles:
    - role: genzer.workspace
      tags:
        - workspace

    - role: genzer.java
      tags:
        - java
      vars:
        jdk_versions:
          - adoptopenjdk8
          - adoptopenjdk13

    - role: genzer.terminal
      tags:
        - terminal

    - role: genzer.aws
      tags: ['aws']

    - role: genzer.vscode
      tags: ['vscode']

  tasks:
    - import_role:
        name: genzer.java
        tasks_from: install_zulu_jdk.yaml
      tags:
        - java.zulu

