- name: Install all commands using Homebrew.
  hosts: localhost
  tags:
    - commands
  vars:
    homebrew_taps:
      - homebrew/core
      - mike-engel/jwt-cli

    homebrew_installed_packages:
      # Prefer neovim from now on
      # - { name: vim, install_option: "with-override-system-vim" }
      - neovim
      - git
      - git-lfs
      - tmux
      - zsh
      # I no longer loves thefuck.
      # It seems to become less accurate to suggest correct commands.
      # - thefuck
      - ack
      - jenv
      - awscli
      # An awesome utility to ovewrite default `/bin/rm`
      # so that deleted files/directories go to the Trash
      # instead of being permanently deleted.
      - trash
      # utility for installing MacOS application from Store
      # https://github.com/mas-cli/mas
      - mas
      - hadolint
      - findutils
      - todo-txt
      - watch
      - tree
      - jq
      # Previously python-yq but I changed
      - yq
      - go
      - gnu-sed
      - maven
      - wget
      - gradle
      - groovy
      - asciinema
      - htop
      # For developing AWS Lambda
      - serverless
      - python@3.8
      - python@3.9
      - python@3.10
      # VSCode PlantUML Preview
      - graphviz
      # A useful to see Disk Usage
      - ncdu
      - jwt-cli
      - bat
      - openshift-cli
      # Replace old Bash (3.2) on macOS
      # with newer version.
      - bash
      # A lighter and faster version of `nvm`.
      - fnm
      # A better replacement for df. Because df on MacOS sucks.
      - duf
      # GitHub CLI
      - gh
      - helm
      # aria2 is a file-downloading cli that support mutliple
      # connections (unlike curl or wget).
      - aria2
      # MacOS Catalina uses GNU Make 3.18 which is old.
      # Install later version v4.x
      - make
      # Starship works wonder with Alacritty
      - starship
      - hurl
      - xsv
      - neofetch
      - aws-vault

    homebrew_uninstalled_packages:
      # antigen slows down the startup time of zsh.
      - antigen
      - powerlevel9k
      - nvm
      - vim
      - thefuck

  pre_tasks:
    - name: Ensure ask-become-pass is working
      shell: id
      become: True
  roles:
    - geerlingguy.homebrew

- name: Installing MacOS Applications using Homebrew.
  hosts: localhost
  tags:
    - apps
  vars:
    homebrew_taps:
      - homebrew/cask-versions
      - homebrew/cask-fonts
    homebrew_cask_apps:
      - google-chrome
      - sublime-text 
      # Favor Alacritty
      # - iterm2
      - alacritty
      - skype
      - postman
      - visual-studio-code
      - slack
      - viscosity
      - vlc
      - keka
      - the-unarchiver
      # - franz
      - xquartz
      - typora
      - teamviewer
      - snagit
      - enpass
      - onedrive
      - keycastr
      - docker
      - balsamiq-wireframes
        #- font-fira-mono
        #- font-fira-mono-for-powerline
      - google-backup-and-sync
      - gas-mask
      - adobe-acrobat-reader
      - robo-3t
      - font-hack-nerd-font
      - angry-ip-scanner
      - visualvm
      - ngrok
      - webex-meetings
      - microsoft-teams
      - pgadmin4
        #- font-firacode-nerd-font
        #- font-hasklug-nerd-font
      - font-jetbrains-mono
      - font-jetbrains-mono-nerd-font
      - telegram-desktop
      - shiftit
      - fanny
      - vitals
      - vanilla
      - obsidian
      - brave-browser

  pre_tasks:
    - name: Ensure ask-become-pass is working
      shell: id
      become: True
  roles:
    - geerlingguy.homebrew

- name: Setting up workspace.
  hosts: localhost
  tags:
    - workspace
  roles:
    - role: genzer.workspace
      tags:
        - workspace.apps

    - role: genzer.java
      tags:
        - java
      vars:
        jdk_versions:
          - adoptopenjdk8
          - adoptopenjdk11
          - adoptopenjdk13
          - adoptopenjdk17

    - role: genzer.terminal
      tags:
        - terminal

    - role: genzer.aws
      tags: ['aws']

    - role: genzer.vscode
      tags: ['vscode']

  tasks:
    - import_role:
        name: genzer.java
        tasks_from: install_zulu_jdk.yaml
      tags:
        - java.zulu

