- name: Install all applications using Homebrew cask.
  hosts: localhost
  tags:
    - installing-apps
  vars:

    homebrew_taps:
      - homebrew/core
      - homebrew/cask-versions
      - homebrew/cask-fonts

    homebrew_installed_packages:
      - { name: vim, install_option: "with-override-system-vim" }
      - git
      - tmux
      - zsh
      - thefuck
      - ack
      - jenv
      - awscli
      # An awesome utility to ovewrite default `/bin/rm`
      # so that deleted files/directories go to the Trash
      # instead of being permanently deleted.
      - trash
      # utility for installing MacOS application from Store
      # https://github.com/mas-cli/mas
      - mas
      - hadolint
      - nvm
      - findutils
      - todo-txt
      - watch
      - tree

    homebrew_uninstalled_packages:
      # antigen slows down the startup time of zsh.
      - antigen
      - powerlevel9k

    homebrew_cask_apps:
      - google-chrome
      - sublime-text 
      - iterm2
      - skype
      - postman
      - visual-studio-code
      - slack
      - viscosity
      - vlc
      - keka
      - the-unarchiver
      - franz
      - xquartz
      - typora
      - teamviewer
      - snagit
      - enpass
      - onedrive
      - keycastr
      - docker
      - balsamiq-mockups
      - font-fira-mono
      - font-fira-mono-for-powerline
      - google-backup-and-sync
      - gas-mask
      - adobe-acrobat-reader
      - robo-3t
      - font-hack-nerd-font

  pre_tasks:
    - name: Ensure ask-become-pass is working
      shell: id
      become: True

  roles:
    - geerlingguy.homebrew

- name: Setting up workspace.
  hosts: localhost
  tags:
    - workspace
  roles:
    - genzer.workspace
    - { role: genzer.terminal, tags: ['terminal'] }
    - { role: genzer.aws, tags: ['aws'] }
    - { role: genzer.vscode, tags: ['vscode'] }

