- name: Install Tmux Plugin Manager
  tags:
    - tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    ssh_opts: '-o StrictHostKeyChecking=no'
    update: False
